# this script based off of https://github.com/tolbertam/mocha-appveyor-reporter/blob/master/appveyor.yml

branches:
  except:
    - gh-pages

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - '*.md'
    - 'CHANGELOG'

image:
- Visual Studio 2017
- Ubuntu

stack: node 8, python 3.6
environment:
  nodejs_version: "8"

install:
  - npm install

build: off

test_script:
  - npm run appveyorTest

cache:
  - node_modules -> package.json

notifications:
  - provider: Email
    to:
      - almenon214@gmail.com
    on_build_success: false
    
skip_commits:
  files:
    - '**/*.md'
